version: '3.8'

services:
  sbt:
    build:
      context: ../
      dockerfile: ../Dockerfile
    command: sbt run
    image: sbt
    ports:
      - "8080:8080"
    volumes:
      - "../:/root/build"
